### PR TITLE
fixed Auto-pan while wiring or placing components #255

### PR DESCRIPTION
**Pull request by emrankb**
I fixed it to automatically pan into the direction of the mouse if the latter hits the screen border while one is wiring or placing components. Pretty cool enhancement. Saves you the hustle.

### CODE REVIEW

**Comment by emrankb** [comment]
I fixed it by adding a new rectangle and Making the newly created rectangle the new visible canvas. This was done in  src/main/java/com/cburch/logisim/gui/main/Canvas.java  in the function named dragged.  Here is the code I added:
————————
Rectangle r = new Rectangle(e.getX(), e.getY(), 1, 1);
 scrollRectToVisible(r);
————————-

How I tested that it works is by dragging a wire outside of the visible canvas and it did automatically moved the scroller so that the wiring can continue. Which it didn’t before. Before this fix you had to manually move the scroller which could be more work since you have to let go off the dragging.

**Comment by BFH-ktt1** [comment]
It is indeed a nifty feature. Unfortunately when I tested it, I saw that it is working correctly by a zoom-level of 100%. Changing the zoom level to something else than 100% will result in a "strange behavior" in the sense that it will pan to the left (with jumps), but not to the right. Without looking into details, I guess that the mouse coordinates (e.getX() and e.getY()) need to be scaled with the zoom-factor.
If you could fix this behavior I am very happy to merge your nifty feature.

**Comment by emrankb** [comment]
I found a fix for that @BFH-ktt1

**Comment by emrankb** [comment]
I appreciate!! @BFH-ktt1

**Pull request merged**
