### PR TITLE
Logisim-evolution with FSM editor

### PR DESCRIPTION
**Pull request by sderrien**
Hello, 

As suggested by torsten, I commited a version of logisim based on the develop branch of logisim-reid, where I omitted the generated files and additional libraries requires by xtednt/xtext framework.
 
https://github.com/reds-heig/logisim-evolution/issues/6#issuecomment-458088022

Regards,

### CODE REVIEW

**Comment by maehne** [comment]
Thanks @sderrien for submitting the PR so that we all can work together to bring this feature to a conflict-free and mature enough state for integration into our `develop` branch. At the end of this process, we may consider to squash the commits in this PR before merging to further clean-up the Git history.

@all: Currently, this PR does not yet build without errors. So, don't merge it yet!

**Comment by BFH-ktt1** [comment]
Unfortunatly the merged version did brake the gradle system and did not compile versus the current development branch.
I have to look into the details what is going on, but this might take some time.

**Comment by BFH-ktt1** [comment]
@sderrien, Sorry, I cannot reopen the pull request, could you please do a new one with reference to this one (#217).
Thanks and sorry for the circumstances.

**Comment by maehne** [comment]
@sderrien's branch [`dev-with-fsm`](https://github.com/sderrien/logisim-evolution/tree/dev-with-fsm) is still available in his fork. It is based on a version before we migrated to gradle as a build system. I think the best tactic would be to bring it slowly in sync with our develop branch, i.e.:

1. Add his [fork](https://github.com/sderrien/logisim-evolution) as a remote
2. Create a local branch `dev-with-fsm`, which follows his branch
3. Check the state of his branch. Does it build? How? What additional dependencies are needed compared to the original Logisim-evolution branch? Fix the build issues.
4. Progressively merge Logisim-evolution's improvements into that branch. Commits that did modification to the gradle build scripts are good candidates for that, as they might break again the build.
5. Once the `dev-with-fsm` branch is in sync with the gradle build system in develop, it is probably possible to merge the HEAD of `develop`.

If I remember correctly, the FSM editor used some Eclipse frameworks and @sderrien was building his fork from within Eclipse instead of using gradle. I had started looking into that, but never found the time to continue the work over the past 1.5 years.

**Pull request merged**
