### PR TITLE
Add 74LS161 Device

### PR DESCRIPTION
**Pull request by GavinAndrews**
OK... so I downloaded logisim yesterday and discovered it did not have a device I really need... so today I added this!

This is my first commit so please review carefully

### CODE REVIEW

**Comment by GavinAndrews** [comment]
Datasheet https://www.ti.com/lit/ds/symlink/sn54ls161a-sp.pdf?ts=1621371900025&ref_url=https%253A%252F%252Fwww.google.fr%252F

**Comment by BFH-ktt1** [comment]
Please make a push-request against the development tree. We use the master tree to keep track of the code of the latest stable version. Thanks in advance.

**Comment by GavinAndrews** [comment]
Moved PR and my changes onto origin/develop

**Comment by GavinAndrews** [comment]
I'm not sure the behaviour is exactly right... this needs review by someone familiar with 74LS161

**Pull request merged**
