### PR TITLE
French localization fixes and key fixes

### PR DESCRIPTION
**Pull request by zdimension**
Some fixes in French translations but most importantly fixes for all languages related to invalid .properties keys, for example keys that contained spaces (and as such weren't recognized, leading to the default English value being used no matter the UI language)

### CODE REVIEW

**Comment by maehne** [comment]
Thanks a lot @zdimension for your pull request! Your corrections are highly appreciated and feedback and contributions are always welcome. @BFH-ktt1: From my side the PR looks good. You might want to check it, too. There are some lines in the property files, which are deleted without replacement and I suspect were not actually used. Maybe, I overlooked something.

**Review by maehne — APPROVED** [review]
From my side the PR looks good. You might want to check it, too. There are some lines in the property files, which are deleted without replacement and I suspect were not actually used. Maybe, I overlooked something.

**Comment by zdimension** [comment]
Yes, some lines were deleted in the Polish localization files. For some reason, that language seemed to contain lines that were not used anywhere in the project, and that weren't present in other languages' files. If needed, I can add the lines back.

**Comment by maehne** [comment]
Thanks @zdimension for the quick reply to my feedback. I am fine with removing lines with unused translations.

**Pull request merged**
