### PR TITLE
Corrected Typo in Documentation --  "Vactor" to "Vector"

### PR DESCRIPTION
**Pull request by evank28**
Simple PR to update spelling in documentation,

### CODE REVIEW

**Comment by maehne** [comment]
Thanks for fixing that typo! While you are at it, could you please also fix the typo "Simulata" -> "Simulate" on the same line?

**Comment by evank28** [comment]
Done. @maehne

**Review by maehne — APPROVED** [review]
Looks good to me. Thanks!

**Comment by BFH-ktt1** [comment]
@evank28 : Could you please make a pull-request for the development branch. The master branch only contains the the releases. The current development branch will be merged with the master branch the next time we do a new release.
Thanks

**Comment by evank28** [comment]
Alright, I've switched this PR to the develop branch. @BFH-ktt1

**Pull request merged**
