### PR TITLE
Use standard ResourceBundle directory structure

### PR DESCRIPTION
**Pull request by zdimension**
The current codebase uses a non-standard way of handling localization .properties files, which does not conform to the standard Java file structure and thus prevent using standard localization editors since they don't recognize the folder structure.

This change has no functional impact on the program, its only purpose is only to allow detection of bundles by bundle editors (which, in turn, allows for spotting missing translations more easily).

Moreover, the handling of "fallback" (missing) translations, which was previously done in LocaleManager, is now handled by Java natively.

Current hierarchy:

- logisim
  - en
    - std.properties
    - gui.properties
    - ...
  - fr
    - std.properties  
    - ...
  - de
  - ...

New hierarchy:

- logisim
  - strings
    - std
      - std.properties
      - std_fr.properties
      - std_de.properties
      - ...
    - gui 
      - ...
    - ...

### CODE REVIEW

**Comment by maehne** [comment]
Thanks @zdimension for this PR! The proposed simplification and alignment of the localisation with standard Java conventions is appreciated. There are two pending PRs #482 and #483, which propose modifications to the localisation, which should first get merged. Especially the new Japanese localisation by @Narita-1095305 should be taken into account by this PR.

**Comment by zdimension** [comment]
Okay, once those two PRs are merged, I'll merge back the changes into this one. Is that okay?

**Comment by maehne** [comment]
> Okay, once those two PRs are merged, I'll merge back the changes into this one. Is that okay?

Yes, that would be great! Thanks!

**Comment by maehne** [comment]
@zdimension: The `develop` branch is now up-to-date thanks to @BFH-ktt1. Please rebase your PR and take the new Japanese localisation into account. Thanks!

**Comment by zdimension** [comment]
The Japanese localization has been added to the new structure. Everything seems to work fine, though I get encoding problems when running locally:
image
Is it a problem on my side? (the problem is not related to my changes, I get it if I checkout develop on the latest commit)

**Comment by BFH-ktt1** [comment]
I did not check it on all platforms, but on my ubuntu 20.04 LTS it looks like:
Screenshot from 2021-01-27 18-28-35

**Comment by Narita-1095305** [comment]
My PC can show Japanese Normally.

**Comment by BFH-ktt1** [comment]
@zdimension , you mentioned "using standard localization editors". Do you have some pointers to them?

**Comment by zdimension** [comment]
@Narita-1095305 then it should be a font problem, related to the UI using Arial or something like that which doesn't support many CJK chars

@BFH-ktt1 I personally use the one integrated in IntelliJ:
image
There's also a very good plugin for Eclipse which pretty much does the same thing. In IntelliJ you can ask it to show only incomplete translations (keys that are missing a value for one or more languages) and it can also tell you if a key is never used, etc.

**Pull request merged**
